---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-fme-kv
spec:
  provider:
    azurekv:
      environmentType: PublicCloud
      authType: ManagedIdentity
      vaultUrl: https://eng2024-infra-keyvault.vault.azure.net/