apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://git@github.com:jsw1993/eng2024.git.git'
      targetRevision: dev
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 65.1.0
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
        - $values/argo/clusters/eng2024-aks/kube-prometheus-stack.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd