---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./flux/bases/bitnami
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
