---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 60m0s
  path: ../../overlays/eng2024-aks/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 60m0s
  path: ../../overlays/eng2024-aks/cert-manager-issuer
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
