---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 60m0s
  path: ../../overlays/eng2024-aks/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 60m0s
  path: ../../overlays/eng2024-aks/external-secrets-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
