---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: bitnami
  interval: 60m0s
  path: ./flux/overlays/eng2024-aks/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
