---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./flux/overlays/eng2024-aks/ingress-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
