---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      version: "1.15.3"
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: kube-system
      interval: 1m
  values:
    crds:
      enabled: true
      keep: true
    prometheus:
      enabled: false
