apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: eng-flux-ci-demo
  labels:
    app: eng-flux-ci-demo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: eng-flux-ci-demo
  selector:
    app: eng-flux-ci-demo
